### ISSUE TITLE
Add audio to the cards

### ISSUE THREAD

**Issue by JimHalen** [FreeLanguageTools/ssmtool#2]
An awesome tool that you made, I would like to say that before anything! Thank you! I would suggest that you make a way, that the tool can add audio to the cards, I didn't find a way to that than manually.

**Comment by 1over137** [comment]
> An awesome tool that you made, I would like to say that before anything! Thank you! I would suggest that you make a way, that the tool can add audio to the cards, I didn't find a way to that than manually.

Check out this link for the full set of features supported.
https://freelanguagetools.org/posts/ssmtool-full-tutorial/
We currently do not support adding audio, but you can do it automatically by configuring AwesomeTTS to add them to your note type during review.

https://ankiweb.net/shared/info/1436550454
https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/On-the-fly-TTS

Personally I use google wavenet voice, the pronunciation is very clear.
I might just integrate this into ssmtool at some point, but I need a way to circumvent the api key requirement
